language: cpp

sudo: false

compiler:
 - clang
 - gcc

env:
 - BUILDTYPE: Debug
 - BUILDTYPE: Release

addons:
  coverity_scan:
    project:
      name: "${TRAVIS_REPO_SLUG}"
      description: "Build submitted via Travis CI"
    notification_email: 4f7f3a820da643d180486972f68a251f.protect@whoisguard.com
    build_command_prepend: "cov-configure --comptype g++ --compiler g++-4.9 --template && cd build"
    build_command: "make -j2"
    branch_pattern: master
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.8
     - george-edison55-precise-backports
    packages:
     - g++-4.9
     - gcc-4.9
     - clang-3.8
     - cmake
     - cmake-data
     - xorg-dev
     - libgl1-mesa-glx
     - libgl1-mesa-dev
     - lcov

cache: apt

before_install:
 - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
 - gem install coveralls-lcov

before_script:
 - if [[ ${CXX} == "g++" ]]; then 
       export CXX="g++-4.9" CC="gcc-4.9" ; 
       if [[ ${COVERALLS_TOKEN} != "" && ${BUILDTYPE} == "Debug" ]]; then
           export COVERAGE="1" ;
           export CXXFLAGS="--coverage" ;
           echo "Coverage enabled." ;
       fi
   fi
 - if [[ ${CXX} == "clang++" ]]; then export CXX="clang++-3.8" CC="clang-3.8" ; fi
 - ( mkdir -p build && cd build ; cmake .. -DCMAKE_BUILD_TYPE=${BUILDTYPE} )

script:
 - cd ${TRAVIS_BUILD_DIR}/build
 - make -j2
 - ./tests
 - if [[ ${COVERAGE} == "1" ]]; then
       lcov -q --directory . --base-directory ../include/mapbox --no-external --capture --output-file coverage.info ;
       lcov --list coverage.info ;
       coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info ;
   fi
 - ./bench
