language: cpp

sudo: false

cache: apt

before_script:
  - if [[ ${CXX_COMPILER} != "" ]]; then export CXX=${CXX_COMPILER} ; fi
  - if [[ ${CC_COMPILER} != "" ]]; then export CC=${CC_COMPILER} ; fi
  - if [[ ${COMPILER_FLAGS} != "" ]]; then export CXXFLAGS=${COMPILER_FLAGS} ; fi
  - ( mkdir -p build && cd build ; cmake .. -DCMAKE_BUILD_TYPE=${BUILDTYPE} )
  - if [[ -n $COVERITY_SCAN_PROJECT_NAME ]] ; then curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true ; fi

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make -j2
  - ./tests
  - if [[ ${COVERAGE} == "1" ]]; then
      lcov -q --directory . --base-directory ../include/mapbox --no-external --capture --output-file coverage.info ;
      lcov --list coverage.info ;
      coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info ;
    fi
  - ./bench

addons:
  apt:
    sources: &shared_linux_sources
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages: &shared_linux_packages
      - cmake
      - cmake-data
      - xorg-dev
      - libgl1-mesa-glx
      - libgl1-mesa-dev

matrix:
  fast_finish: true
  include:
    # clang debug
    - os: linux
      env: BUILDTYPE=Debug CXX_COMPILER=clang++-3.8 CC_COMPILER=clang-3.8
      compiler: clang
      addons:
        apt:
          sources:
            - *shared_linux_sources
            - llvm-toolchain-precise-3.8
          packages:
            - *shared_linux_packages
            - clang-3.8

    # clang release
    - os: linux
      env: BUILDTYPE=Release CXX_COMPILER=clang++-3.8 CC_COMPILER=clang-3.8
      compiler: clang
      addons:
        apt:
          sources:
            - *shared_linux_sources
            - llvm-toolchain-precise-3.8
          packages:
            - *shared_linux_packages
            - clang-3.8

    # gnu debug with coverage
    - os: linux
      env: BUILDTYPE=Debug CXX_COMPILER=g++-4.9 CC_COMPILER=gcc-4.9 COVERAGE=1 COMPILER_FLAGS=--coverage
      compiler: gcc
      addons:
        apt:
          sources:
            - *shared_linux_sources
          packages:
            - *shared_linux_packages
            - &gnu_packages [g++-4.9, gcc-4.9]
            - lcov
      install:
        - gem install coveralls-lcov

    # gnu release with coverity
    - os: linux
      env: 
        - BUILDTYPE=Release 
        - CXX_COMPILER=g++-4.9 
        - CC_COMPILER=gcc-4.9
        - COVERITY_SCAN_PROJECT_NAME="${TRAVIS_REPO_SLUG}"
        - COVERITY_SCAN_BRANCH_PATTERN="master"
        - COVERITY_SCAN_NOTIFICATION_EMAIL="4f7f3a820da643d180486972f68a251f.protect@whoisguard.com"
        - COVERITY_SCAN_BUILD_COMMAND_PREPEND="cov-configure --comptype g++ --compiler g++-4.9 --template && cd build"
        - COVERITY_SCAN_BUILD_COMMAND="make -j2"
      compiler: gcc
      addons:
        apt:
          sources:
            - *shared_linux_sources
          packages:
            - *shared_linux_packages
            - *gnu_packages
      before_install:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

    # osx gcc
    - os: osx
      osx_image: xcode8.3
      env: BUILDTYPE=Release CXX_COMPILER=g++ CC_COMPILER=gcc
      compiler: gcc
    
    # osx clang
    - os: osx
      osx_image: xcode8.3
      env: BUILDTYPE=Release CXX_COMPILER=clang++ CC_COMPILER=clang
      compiler: clang
      