os: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017"
    - GENERATOR: "Visual Studio 15 2017 Win64"
    - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "Visual Studio 12 2013 Win64"
    - GENERATOR: "MinGW Makefiles"

matrix:
  fast_finish: true

install:
  - git submodule update --init

build_script:
  - cmake -H. -Bbuild -G"%GENERATOR%"
  - cmake --build build --config Release

test_script:
  - call "build/Release/tests.exe"
  - call "build/Release/bench.exe"